/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GTA */

#ifndef _Included_GTA
#define _Included_GTA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GTA
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_GTA_init(JNIEnv *, jobject);

/*
 * Class:     GTA
 * Method:    kill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GTA_kill(JNIEnv *, jobject);

/*
 * Class:     GTA
 * Method:    onFoot
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_GTA_onFoot(JNIEnv *, jobject);

/*
 * Class:     GTA
 * Method:    getX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_GTA_getX(JNIEnv *, jobject);

/*
 * Class:     GTA
 * Method:    getY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_GTA_getY(JNIEnv *, jobject);

/*
 * Class:     GTA
 * Method:    getZ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_GTA_getRotation(JNIEnv *, jobject);

/*
 * Class:     GTA
 * Method:    getHealth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_GTA_getHealth(JNIEnv *, jobject);

/*
 * Class:     GTA
 * Method:    getCars
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_GTA_getCars(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

class GTA {
public:
	GTA();
	virtual ~GTA();
};
#endif

